### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by timjacobi** [mstahv/consuming-rest-apis#1]
It would be interesting to see how you test this. Could you provide an example? Thanks

**Comment by mstahv** [comment]
Testing of what? For automated integration/acceptance testing of the UI and whole app, I'd suggest to look at [Vaadin TestBench](https://vaadin.com/add-ons/testbench). You can go with plain Selenium as well, but TestBench has some nice helpers that makes building test scripts faster.

Check e.g. this example project: https://github.com/mstahv/tb-page-object
