### ISSUE TITLE
OpenWeather API authentication fails 

### ISSUE THREAD

**Issue by abhirockzz** [mstahv/consuming-rest-apis#3]
This happens despite the presence of API Key in src/main/resources/META-INF/apache-deltaspike.properties - end up with a HTTP 401 (as expected)

Forced to add the api key as APPID query param (as suggested here http://openweathermap.org/appid#use)

**Comment by mstahv** [comment]
Hmm, it works for me. That's done here: https://github.com/mstahv/consuming-rest-apis/blob/master/src/main/java/org/example/JsonService.java#L33

I guess for some reason the property injection is not working for you. Which server are you using?

**Comment by abhirockzz** [comment]
It works. Not sure what was happening before ! Sorry for the trouble
